### PR TITLE
[ENH] ADD INDI node

### PR DESCRIPTION
**Pull request by surchs**
- See https://github.com/neurobagel/planning/issues/119

Changes proposed in this pull request:

-
-

## Checklist

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

**Comment by surchs** [comment]
Still needs NGINX configured before indi.neurobagel.org actually responds

**Comment by alyssadai** [comment]
NGINX + HTTPS has been configured, https://indi.neurobagel.org now responds :)

Switching this PR to ready for review.

**Review by alyssadai — APPROVED** [review]
Looks good! 🧑‍🍳 I ran some test queries via the API and all seems to be working as expected 🎉 

Have another look at the `"NodeName"` - maybe we could use the full name for INDI instead?

**Comment by alyssadai** [comment]
I'll redeploy the f-API once this is merged.

**Comment by surchs** [comment]
> Have another look at the "NodeName" - maybe we could use the full name for INDI instead?

Agree. How about
- FCP/INDI OR
- International Neuroimaging Data-sharing Initiative

Not sure either is widely known at this point - and the second one might be a bit too long for most of our UI elements?

**Comment by alyssadai** [comment]
@surchs I vote for the latter even though it's a bit long - it'd also be consistent with us using full names for our other nodes 🤷

**Pull request merged**
